# postgresql.conf - Ambiente de Estudos

listen_addresses = '*'
port = 5432

# Ambiente para replicação
max_wal_senders = 10
max_replication_slots = 10
wal_keep_size = 256MB          # ou maior se a réplica puder ficar atrasada
hot_standby = on               # útil se um dia promover a réplica

# Memória (ajuste conforme seu notebook)
shared_buffers = 256MB
work_mem = 16MB
maintenance_work_mem = 128MB

# WAL e Checkpoint (importante para capítulos futuros)
wal_level = replica
max_wal_size = 1GB
min_wal_size = 80MB
checkpoint_timeout = 15min

# Archive Mode
archive_mode = off #on
archive_command = '' #'test ! -f /var/lib/postgresql/wal_archive/%f && cp %p /var/lib/postgresql/wal_archive/%f'

# Logging (útil para troubleshooting)
logging_collector = off  # on
log_directory = 'log'
log_filename = 'postgresql-%Y-%m-%d.log'
log_statement = 'ddl'
log_min_duration_statement = 1000

# Carga de extensions
shared_preload_libraries = 'pg_stat_statements'

