# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Local
local   all             all                                     trust
host    all             all             127.0.0.1/32            trust
host    all             all             ::1/128                 trust

# Rede Citus (coordenador + workers)
host    all             all             172.30.0.0/16           trust
host    replication     all             172.30.0.0/16           trust

# (Opcional) acesso externo via porta publicada — restrinja em produção
#host    all             all             0.0.0.0/0               scram-sha-256