# postgresql.conf - Ambiente de Estudos

listen_addresses = '*'
port = 5432

# Memória (ajuste conforme seu notebook)
shared_buffers = 256MB
work_mem = 16MB
maintenance_work_mem = 128MB

# WAL e Checkpoint (importante para capítulos futuros)
wal_level = replica
max_wal_size = 1GB
min_wal_size = 80MB
checkpoint_timeout = 15min

# Archive Mode
archive_mode = off #on
archive_command = '' #'test ! -f /var/lib/postgresql/wal_archive/%f && cp %p /var/lib/postgresql/wal_archive/%f'

# Logging (útil para troubleshooting)
logging_collector = off  # on
log_directory = 'log'
log_filename = 'postgresql-%Y-%m-%d.log'
log_statement = 'ddl'
log_min_duration_statement = 1000

# Carga de extentions
shared_preload_libraries = 'pg_stat_statements'

#### Configurações de Replicação (Réplica)
# Obrigatório para aceitar queries enquanto aplica o WAL
hot_standby = on

# Recomendado: evita que o vacuum do primary remova linhas ainda usadas pela réplica
hot_standby_feedback = on

# Opcional (mas útil)
max_standby_streaming_delay = 30s   # quanto tempo espera queries longas antes de cancelar
wal_receiver_status_interval = 10s